sentiments = [
    ("Positive", 0),
    ("Hyped", 1),
    ("Laughter", 2),
    ("Negative", 3),
    ("Upset", 4),
    ("Toxic", 5),
    ("Neutral", 6),
    ("Shocked", 7)
]

examples = [("lets go you got this he leaked", 0),
            ("That hat clean Des", 0),
            ("that shit good asl", 0),
            ("EASSYYY LETS GO DESS", 1),
            ("WOWWWWWWWW", 1),
            ("SHOW EM THE DEEP FREEZE LEE", 1),
            ("THEY SHOOK", 1),
            ("BEN PLEASE LMAOO", 2),
            ("BEN SOLDD LOL", 2),
            ("LMFAOOO look at waiting room chat", 2),
            ("daaang bro still at the starting line", 3),
            ("you too little", 3),
            ("your wifi assing out", 3),
            ("fuckkk noooo", 4),
            ("Ben i cant believe it was you bro whyyyyyy", 4),
            ("BEN why did you leak", 4),
            ("Lee u chunky monkey", 5),
            ("you so ass big bro", 5),
            ("big ass lips smacking", 5),
            ("gang these some SHIT recommendations jus play rivals dawg", 6),
            ("Why do you wear a cap in the house big dyl", 6),
            ("hey beautiful I still am trying to find the answer to my question too", 6),
            ("nah would be pretty dumb if he did lmao", 6),
            ("NAH WHAT WAS THAT", 7),
            ("HUHHHHHH", 7),
            ("THATS INSANE", 7)]
